### ISSUE TITLE
Import/Export options don't appear to work.

### ISSUE THREAD

**Issue by SneakyDave** [VersoBit/XF-Badges#14] opened 2020-11-16 13:11 UTC
Not sure what the deal is with this, but I don't have the addon installed anymore.  I reported it on xenforo a year ago.
https://xenforo.com/community/threads/badges.169672/#post-1380130

**Comment by RyleaStark** [comment] 2020-11-16 18:56
Duplicate of #11

**Comment by RyleaStark** [comment] 2020-11-16 18:56
Duplicate of #12

**Closed by RyleaStark** 2020-11-16 18:56 UTC
Labels: bug

**Comment by RyleaStark** [comment] 2020-11-16 19:09
@SneakyDave The original developer never coded these functions in, he did however template the ACP classes which is why it never worked. Planned updates!!
